FROM postgres:alpine
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
EXPOSE ${POSTGRES_PORT}
VOLUME pgdb-data:/var/lib/postgresql/data
RUN mkdir /logs && chown postgres:postgres /logs
VOLUME pgdb-logs:/logs
CMD ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/logs", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
